- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact us"

- name: "Forum EPESI"
  url: "http://forum.epesibim.com"
  title: "Forum EPESI - free help"

- name: "Trial version of EPESI"
  url: "https://trial.epesicrm.com/hosting/"
  title: "Start your own trial version of EPESI!"

- name: "Support"
  url: "/support/"
  title: "How to obtain paid help and assistance"  